create table board (id bigint generated always as identity primary key, public_id text not null unique, name text not null, date_start date not null, date_end date not null, purpose text, status text not null default 'COLLECTING', invite_code text not null unique, invite_expires_at timestamptz not null, public_token text unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table participant (id bigint generated always as identity primary key, public_id text not null unique, board_id bigint not null references board(id), nickname text not null, role text not null, token_hash text not null, avatar_color text not null, active boolean not null default true, origin_label text, origin_ciphertext bytea, origin_source text, origin_provider_place_id text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table place (id bigint generated always as identity primary key, public_id text not null unique, board_id bigint not null references board(id), proposer_id bigint not null references participant(id), name text not null, lon double precision not null, lat double precision not null, address_name text, road_address_name text, internal_category text not null, provider text, provider_place_id text, provider_place_url text, source text not null, status text not null default 'ACTIVE', deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table place_comment (id bigint generated always as identity primary key, public_id text not null unique, place_id bigint not null references place(id), author_id bigint not null references participant(id), body text not null, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table vote (id bigint generated always as identity primary key, public_id text not null unique, board_id bigint not null references board(id), status text not null default 'OPEN', max_selections int not null, anonymous boolean not null, closes_at timestamptz not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table vote_option (id bigint generated always as identity primary key, vote_id bigint not null references vote(id), place_id bigint not null references place(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(vote_id, place_id));
create table vote_ballot (id bigint generated always as identity primary key, vote_id bigint not null references vote(id), participant_id bigint not null references participant(id), option_id bigint not null references vote_option(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(vote_id, participant_id, option_id));
create table area_search_job (id bigint generated always as identity primary key, public_id text not null unique, board_id bigint not null references board(id), status text not null default 'QUEUED', duration_min int not null, snapshot jsonb not null, progress jsonb, result jsonb, error_code text, retry_count int not null default 0, next_retry_at timestamptz, started_at timestamptz, finished_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table area_candidate (id bigint generated always as identity primary key, public_id text not null unique, job_id bigint not null references area_search_job(id), name text not null, lon double precision not null, lat double precision not null, provider_place_id text, metrics jsonb not null, reasons jsonb not null, rank int not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table course_draft (id bigint generated always as identity primary key, board_id bigint not null unique references board(id), version int not null default 0, stops jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table course (id bigint generated always as identity primary key, public_id text not null unique, board_id bigint not null references board(id), version int not null, confirmed_at timestamptz not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(board_id, version));
create table course_stop (id bigint generated always as identity primary key, course_id bigint not null references course(id), place_id bigint not null references place(id), order_index int not null, role text not null, scheduled_at timestamptz not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(course_id, order_index));
create table departure_calculation (id bigint generated always as identity primary key, participant_id bigint not null references participant(id), course_id bigint not null references course(id), status text not null, total_seconds int, transfer_count int, fare_amount int, total_walk_seconds int, recommended_departure_at timestamptz, calculated_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(participant_id, course_id));

create index idx_participant_board on participant(board_id);
create index idx_place_board on place(board_id);
create index idx_place_proposer on place(proposer_id);
create index idx_comment_place on place_comment(place_id);
create index idx_comment_author on place_comment(author_id);
create index idx_vote_board on vote(board_id);
create index idx_vote_option_vote on vote_option(vote_id);
create index idx_vote_option_place on vote_option(place_id);
create index idx_ballot_vote_participant on vote_ballot(vote_id, participant_id);
create index idx_ballot_participant on vote_ballot(participant_id);
create index idx_ballot_option on vote_ballot(option_id);
create index idx_area_job_board on area_search_job(board_id);
create index idx_area_candidate_job on area_candidate(job_id);
create index idx_course_board_version on course(board_id, version desc);
create index idx_course_stop_course on course_stop(course_id);
create index idx_course_stop_place on course_stop(place_id);
create index idx_departure_participant on departure_calculation(participant_id);
create index idx_departure_course on departure_calculation(course_id);
create index idx_place_active on place(board_id, status) where deleted_at is null;
create index idx_comment_active on place_comment(place_id) where deleted_at is null;
create index idx_area_job_poll on area_search_job(status, next_retry_at);
create unique index uq_vote_open_per_board on vote(board_id) where status = 'OPEN';
create unique index uq_area_job_active_per_board on area_search_job(board_id) where status in ('QUEUED','RUNNING','RETRY_WAIT');
